
  mutation createRecipe($title: String!, $description: String, $ingredients: [String!]!) {
    addRecipe(newRecipeData: {
      title: $title
      description: $description
      ingredients: $ingredients
    }
    ) {
      id
      title
      description
      ingredients
    }
  }
